export const categories: Record<string, { english: string; bengali: string }> =
  {
    bangladesh: { english: "Bangladesh", bengali: "বাংলাদেশ" },
    politics: { english: "Politics", bengali: "রাজনীতি" },
    business: { english: "Business", bengali: "ব্যবসা" },
    world: { english: "World", bengali: "বিশ্ব" },
    opinion: { english: "Opinion", bengali: "মতামত" },
    sports: { english: "Sports", bengali: "খেলাধুলা" },
    economy: { english: "Economy", bengali: "অর্থনীতি" },
    education: { english: "Education", bengali: "শিক্ষা" },
    election: { english: "Election", bengali: "নির্বাচন" },
    crime: { english: "Crime", bengali: "অপরাধ" },
    laws: { english: "Laws", bengali: "আইন" },
    government: { english: "Government", bengali: "সরকার" },
    district: { english: "District", bengali: "জেলা" },
    coronavirus: { english: "Coronavirus", bengali: "করোনাভাইরাস" },
    environment: { english: "Environment", bengali: "পরিবেশ" },
    accident: { english: "Accident", bengali: "দুর্ঘটনা" },
    capital: { english: "Capital", bengali: "রাজধানী" },
    market: { english: "Market", bengali: "বাজার" },
    banks: { english: "Banks", bengali: "ব্যাংক" },
    commerce: { english: "Commerce", bengali: "বাণিজ্য" },
    stock: { english: "Stock", bengali: "শেয়ার বাজার" },
    realestate: { english: "Real Estate", bengali: "রিয়েল এস্টেট" },
    industry: { english: "Industry", bengali: "শিল্প" },
    finance: { english: "Finance", bengali: "অর্থ" },
    corporate: { english: "Corporate", bengali: "কর্পোরেট" },
    asia: { english: "Asia", bengali: "এশিয়া" },
    africa: { english: "Africa", bengali: "আফ্রিকা" },
    europe: { english: "Europe", bengali: "ইউরোপ" },
    usa: { english: "USA", bengali: "যুক্তরাষ্ট্র" },
    pakistan: { english: "Pakistan", bengali: "পাকিস্তান" },
    india: { english: "India", bengali: "ভারত" },
    china: { english: "China", bengali: "চীন" },
    australia: { english: "Australia", bengali: "অস্ট্রেলিয়া" },
    memoir: { english: "Memoir", bengali: "স্মৃতিকথা" },
    letter: { english: "Letter", bengali: "চিঠি" },
    reaction: { english: "Reaction", bengali: "প্রতিক্রিয়া" },
    football: { english: "Football", bengali: "ফুটবল" },
    cricket: { english: "Cricket", bengali: "ক্রিকেট" },
    technology: { english: "Technology", bengali: "প্রযুক্তি" },
    health: { english: "Health", bengali: "স্বাস্থ্য" },
    entertainment: { english: "Entertainment", bengali: "বিনোদন" },
    lifestyle: { english: "Lifestyle", bengali: "জীবনযাপন" },
    youth: { english: "Youth", bengali: "যুবা" },
    jobs: { english: "Jobs", bengali: "চাকরি" },
    travel: { english: "Travel", bengali: "ভ্রমণ" },
    science: { english: "Science", bengali: "বিজ্ঞান" },
    startup: { english: "Startup", bengali: "স্টার্টআপ" },
    media: { english: "Media", bengali: "মিডিয়া" },
    editorial: { english: "Editorial", bengali: "সম্পাদকীয়" },
    interview: { english: "Interview", bengali: "সাক্ষাৎকার" },
    analysis: { english: "Analysis", bengali: "বিশ্লেষণ" },
    relation: { english: "Relation", bengali: "সম্পর্ক" },
    beauty: { english: "Beauty", bengali: "সৌন্দর্য" },
    fashion: { english: "Fashion", bengali: "ফ্যাশন" },
    culture: { english: "Culture", bengali: "সংস্কৃতি" },
    music: { english: "Music", bengali: "সঙ্গীত" },
    movies: { english: "Movies", bengali: "চলচ্চিত্র" },
    television: { english: "Television", bengali: "টেলিভিশন" },
    religion: { english: "Religion", bengali: "ধর্ম" },
    literature: { english: "Literature", bengali: "সাহিত্য" },
    campus: { english: "Campus", bengali: "ক্যাম্পাস" },
    projonmo: { english: "Projonmo", bengali: "প্রজন্ম" },
    probash: { english: "Probash", bengali: "প্রবাস" },
    showbiz: { english: "Showbiz", bengali: "শোবিজ" },
    photo: { english: "Photo", bengali: "ছবি" },
    law: { english: "Law", bengali: "আইন" },
    court: { english: "Court", bengali: "আদালত" },
    climate: { english: "Climate", bengali: "জলবায়ু" },
    socialmedia: { english: "Social Media", bengali: "সামাজিক যোগাযোগ মাধ্যম" },
    satire: { english: "Satire", bengali: "বিদ্রূপ" },
    viral: { english: "Viral", bengali: "ভাইরাল" },
    it: { english: "IT", bengali: "আইটি" },
    holiday: { english: "Holiday", bengali: "ছুটি" },
    roundtable: { english: "Roundtable", bengali: "গোলটেবিল" },
    transportation: { english: "Transportation", bengali: "পরিবহন" },
    "gender equality": { english: "Gender Equality", bengali: "লিঙ্গ সমতা" },
    diplomacy: { english: "Diplomacy", bengali: "কূটনীতি" },
    corruption: { english: "Corruption", bengali: "দুর্নীতি" },
    labor: { english: "Labor", bengali: "শ্রম" },
    "human interest": { english: "Human Interest", bengali: "মানবিক আগ্রহ" },
    agriculture: { english: "Agriculture", bengali: "কৃষি" },
    gender: { english: "Gender", bengali: "লিঙ্গ" },
    infrastructure: { english: "Infrastructure", bengali: "অবকাঠামো" },
    workplace: { english: "Workplace", bengali: "কর্মক্ষেত্র" },
    energy: { english: "Energy", bengali: "জ্বালানি" },
    banking: { english: "Banking", bengali: "ব্যাংকিং" },
    cybersecurity: { english: "Cybersecurity", bengali: "সাইবার নিরাপত্তা" },
    migration: { english: "Migration", bengali: "অভিবাসন" },
    obituary: { english: "Obituary", bengali: "মৃত্যু সংবাদ" },
    humanitarian: { english: "Humanitarian", bengali: "মানবিক" },
    work: { english: "Work", bengali: "কাজ" },
  };
