export const APP_NAME = "Sonkhipto";
export const APPSTORE_URL =
  "https://apps.apple.com/us/app/sonkhipto-daily-short-news/id6477333889";

export const GOOGLE_PLAY_URL =
  "https://play.google.com/store/apps/details?id=com.tinybytelabs.sonkhipto";

export const BASE_URL = "https://sonkhipto.com";

export const allCategories: string[] = [
  "bangladesh",
  "politics",
  "business",
  "world",
  "opinion",
  "sports",
  "economy",
  "education",
  "election",
  "crime",
  "laws",
  "government",
  "district",
  "coronavirus",
  "environment",
  "accident",
  "capital",
  "market",
  "banks",
  "commerce",
  "stock",
  "realestate",
  "industry",
  "finance",
  "corporate",
  "asia",
  "africa",
  "europe",
  "usa",
  "pakistan",
  "india",
  "china",
  "australia",
  "memoir",
  "letter",
  "reaction",
  "football",
  "cricket",
  "technology",
  "health",
  "entertainment",
  "lifestyle",
  "youth",
  "jobs",
  "travel",
  "science",
  "startup",
  "media",
  "editorial",
  "interview",
  "analysis",
  "relation",
  "beauty",
  "fashion",
  "culture",
  "music",
  "movies",
  "television",
  "religion",
  "literature",
  "campus",
  "projonmo",
  "probash",
  "showbiz",
  "photo",
  "law",
  "court",
  "climate",
  "environment",
  "socialmedia",
  "satire",
  "viral",
  "it",
  "holiday",
  "roundtable",
];
